# Generated by Django 3.2.9 on 2021-11-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_by', models.CharField(max_length=56)),
                ('title', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
                ('vote_for_issuer', models.CharField(max_length=56)),
                ('vote_against_issuer', models.CharField(max_length=56)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('hide', models.BooleanField(default=False)),
                ('vote_for_result', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('vote_against_result', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimable_balance_id', models.CharField(max_length=72, null=True, unique=True)),
                ('account_issuer', models.CharField(max_length=56, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('vote_choice', models.CharField(choices=[('vote_for', 'Vote For'), ('vote_against', 'Vote Against')], default=None, max_length=15, null=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='governance.proposal')),
            ],
        ),
    ]
