# Generated by Django 3.2.9 on 2021-11-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='text',
            field=models.TextField(),
        ),
    ]
