# Generated by Django 3.2.9 on 2021-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_alter_proposal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_simple_proposal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='vote_against_result',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='vote_for_result',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=20, null=True),
        ),
    ]
