# Generated by Django 3.2.9 on 2021-11-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_auto_20211103_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='logvote',
            name='transaction_link',
            field=models.URLField(null=True),
        ),
    ]
