# Generated by Django 3.2.9 on 2021-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_logvote_transaction_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='transaction_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
