# Generated by Django 3.2.9 on 2021-11-09 07:26

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_proposal_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
