# Generated by Django 3.2.9 on 2021-11-09 07:26
import json

from django.db import migrations
import django_quill.fields
from django_quill.quill import Quill


def refactor_proposal_text(apps, schema_editor):
    proposal_model = apps.get_model('governance', 'Proposal')

    for prop in proposal_model.objects.all():
        try:
            text = prop.text.html
        except Exception:
            text = prop.text.json_string.replace('\r\n', '<br>')
            prop.text = Quill(json.dumps({'delta': '', 'html': '<p>' + text + '</p>'}))
            prop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_proposal_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
        migrations.RunPython(refactor_proposal_text, migrations.RunPython.noop),
    ]
