# Generated by Django 3.2.9 on 2021-11-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_alter_proposal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='aqua_circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=20),
        ),
    ]
