# Generated by Django 3.2.9 on 2021-11-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_proposal_aqua_circulating_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='discord_channel_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='discord_channel_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
