# Generated by Django 3.2.9 on 2021-12-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0008_auto_20211129_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='hidden_after_creation',
            field=models.BooleanField(default=False),
        ),
    ]
