# Generated by Django 3.2.10 on 2021-12-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0010_remove_proposal_hidden_after_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='discord_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
