# Generated by Django 3.2.10 on 2022-02-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0011_proposal_discord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='envelope_xdr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('HORIZON_ERROR', 'Bad horizon response'), ('BAD_MEMO', 'Bad transaction memo'), ('INVALID_PAYMENT', 'Invalid payment'), ('FINE', 'Fine'), ('FAILED_TRANSACTION', 'Transaction unsuccessful')], default='FINE', max_length=64),
        ),
    ]
