# Generated by Django 3.2.10 on 2022-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0012_auto_20220202_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='payment_status',
            field=models.CharField(choices=[('HORIZON_ERROR', 'Bad horizon response'), ('BAD_MEMO', 'Bad transaction memo'), ('INVALID_PAYMENT', 'Invalid payment'), ('FAILED_TRANSACTION', 'Transaction unsuccessful'), ('FINE', 'Fine')], default='FINE', max_length=64),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_status',
            field=models.CharField(choices=[('DISCUSSION', 'Proposal under discussion'), ('VOTING', 'Proposal under voting'), ('VOTED', 'Voted')], default='DISCUSSION', max_length=64),
        ),
    ]
