# Generated by Django 3.2.12 on 2022-03-23 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0012_auto_20220202_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='last_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='payment_status',
            field=models.CharField(choices=[('HORIZON_ERROR', 'Bad horizon response'), ('BAD_MEMO', 'Bad transaction memo'), ('INVALID_PAYMENT', 'Invalid payment'), ('FAILED_TRANSACTION', 'Transaction unsuccessful'), ('FINE', 'Fine')], default='FINE', max_length=64),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_status',
            field=models.CharField(choices=[('DISCUSSION', 'Proposal under discussion'), ('VOTING', 'Proposal under voting'), ('VOTED', 'Voted'), ('EXPIRED', 'Expired')], default='DISCUSSION', max_length=64),
        ),
        migrations.AddField(
            model_name='proposal',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('hide', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256)),
                ('text', django_quill.fields.QuillField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('envelope_xdr', models.TextField(blank=True, null=True)),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_proposal', to='governance.proposal')),
            ],
        ),
    ]
