# Generated by Django 3.2.10 on 2022-03-21 09:34

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0013_auto_20220315_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='HistoryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('hide', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256)),
                ('text', django_quill.fields.QuillField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('envelope_xdr', models.TextField(blank=True, null=True)),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_proposal', to='governance.proposal')),
            ],
        ),
    ]
