# Generated by Django 3.2.12 on 2022-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0013_auto_20220323_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproposal',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
