# Generated by Django 3.2.12 on 2022-05-11 17:02

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0014_alter_historyproposal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='action',
            field=models.CharField(choices=[('TO_UPDATE', 'To update'), ('TO_SUBMIT', 'To submit'), ('TO_CREATE', 'To create'), ('NONE', 'None')], default='NONE', max_length=64),
        ),
        migrations.AddField(
            model_name='proposal',
            name='new_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='new_envelope_xdr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='new_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='new_text',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='new_title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='new_transaction_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
