# Generated by Django 3.2.10 on 2022-03-22 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0014_auto_20220321_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='last_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_status',
            field=models.CharField(choices=[('DISCUSSION', 'Proposal under discussion'), ('VOTING', 'Proposal under voting'), ('VOTED', 'Voted'), ('EXPIRED', 'Expired')], default='DISCUSSION', max_length=64),
        ),
    ]
