# Generated by Django 3.2.12 on 2022-08-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0016_logvote_asset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='ice_circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='percent_for_quorum',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
