# Generated by Django 3.2.12 on 2022-08-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0017_auto_20220815_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='logvote',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logvote',
            name='claimable_balance_id',
            field=models.CharField(max_length=72, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='logvote',
            unique_together={('hide', 'claimable_balance_id')},
        ),
    ]
