# Generated by Django 3.2.12 on 2023-01-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0018_auto_20220819_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='discord_channel_url',
            field=models.URLField(blank=True, default='https://discord.com/channels/862710317825392660/1046931670458187836', null=True),
        ),
    ]
