# Generated by Django 3.2.25 on 2025-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0019_alter_proposal_discord_channel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logvote',
            name='asset_code',
            field=models.CharField(choices=[('AQUA', 'AQUA'), ('governICE', 'governICE'), ('gdICE', 'gdICE')], default='AQUA', max_length=15),
        ),
    ]
