# Generated by Django 3.2.25 on 2025-10-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0020_alter_logvote_asset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logvote',
            name='hide',
            field=models.BooleanField(default=False, help_text='System managed soft exclusion for this vote. Use cases: votes parsed after proposal end; duplicates reingested with the same claimable_balance_id; votes invalidated after rule changes or failed reverification; spam or abuse detection; temporary suppression during reprocessing. When True, the vote remains stored but is excluded from public endpoints and all counts or quorum. Automatically set by parser or background tasks; not edited manually. Part of the composite uniqueness with claimable_balance_id to allow a hidden shadow row without conflicts.'),
        ),
    ]
