# Generated by Django 3.2.25 on 2025-11-10 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0021_alter_logvote_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='logvote',
            name='time_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(default=None, null=True), default=list, size=None),
        ),
    ]
