# Generated by Django 3.2.25 on 2025-11-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0022_logvote_time_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='logvote',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logvote',
            name='group_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logvote',
            name='key',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='logvote',
            name='last_update_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='logvote',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='logvote',
            name='sponsor',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
