# Generated by Django 3.2.25 on 2025-11-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0022_logvote_time_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='logvote',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
