# Generated by Django 3.2.23 on 2026-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0023_auto_20251127_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='abstain_issuer',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vote_abstain_result',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logvote',
            name='vote_choice',
            field=models.CharField(choices=[('vote_for', 'Vote For'), ('vote_against', 'Vote Against'), ('vote_abstain', 'Vote Abstain')], default=None, max_length=15, null=True),
        ),
    ]
