# Generated by Django 3.2.25 on 2025-12-02 10:05

from django.db import migrations

def delete_hide_votes(apps, _):
    LogVote = apps.get_model('governance', 'LogVote')
    LogVote.objects.filter(hide=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0023_auto_20251127_1130'),
    ]

    operations = [
        migrations.RunPython(delete_hide_votes, migrations.RunPython.noop),
    ]
