# Generated by Django 3.2.25 on 2025-12-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0024_auto_20251202_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logvote',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Current claimable balance amount fetched from Horizon at the time of the last synchronization.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logvote',
            name='claimed',
            field=models.BooleanField(default=False, help_text='Indicates that the vote is no longer active (the balance is unavailable/not found during synchronization) and is excluded from the tally.'),
        ),
        migrations.AlterField(
            model_name='logvote',
            name='group_index',
            field=models.IntegerField(default=0, help_text='Vote index within a group sharing the same key. The group is sorted by amount in descending order; 0 is the record with the largest amount.'),
        ),
        migrations.AlterField(
            model_name='logvote',
            name='key',
            field=models.CharField(help_text='Unique vote key. Constructed from: proposal_id|vote_choice|account_issuer|asset|sorted(time_list). Used to group related claimable balances into one logical vote group.', max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='logvote',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Original claimable balance amount from the create_claimable_balance operation (or from the balance record if the operation is unavailable).', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logvote',
            name='voted_amount',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Amount counted in the vote tally during freezing. May be null if the vote has not been frozen yet.', max_digits=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='logvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='logvote',
            name='hide',
        ),
    ]
