# Generated by Django 3.2.25 on 2026-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0025_zero_aqua_supply_for_proposal_125'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='asset_aquarius_traction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_audit_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_community_references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_contract_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_holder_distribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_issuer',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_issuer_commitments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_issuer_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_liquidity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_related_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_stellar_flags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_token_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_trading_volume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_poll_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_status',
            field=models.CharField(
                choices=[
                    ('NOT_REQUIRED', 'No execution required'),
                    ('PENDING', 'Pending execution'),
                    ('IN_PROGRESS', 'Execution in progress'),
                    ('SUBMITTED', 'Transaction submitted'),
                    ('SUCCESS', 'Execution succeeded'),
                    ('FAILED', 'Execution failed'),
                    ('REQUIRES_REVIEW', 'Execution requires review'),
                    ('SKIPPED', 'Execution skipped'),
                ],
                default='NOT_REQUIRED',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_tx_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(
                choices=[
                    ('GENERAL', 'General proposal'),
                    ('ADD_ASSET', 'Add asset proposal'),
                    ('REMOVE_ASSET', 'Remove asset proposal'),
                ],
                db_index=True,
                default='GENERAL',
                max_length=32,
            ),
        ),
    ]
