# Generated by Django 3.2.25 on 2026-02-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0025_zero_aqua_supply_for_proposal_125'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_address', models.CharField(max_length=56, unique=True)),
                ('asset_code', models.CharField(blank=True, max_length=12)),
                ('asset_issuer', models.CharField(blank=True, max_length=56)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('allowed', 'Allowed'), ('denied', 'Denied')], default='unknown', max_length=10)),
                ('added_ledger', models.PositiveIntegerField(default=0)),
                ('updated_ledger', models.PositiveIntegerField(default=0)),
                ('last_proposal_id', models.BigIntegerField(blank=True, null=True)),
                ('meta_hash', models.CharField(blank=True, max_length=64)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ASSET_WHITELIST', 'Asset Whitelist'), ('ASSET_REVOCATION', 'Asset Revocation')], default='GENERAL', max_length=32),
        ),
        migrations.AddField(
            model_name='proposal',
            name='target_asset_address',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.CreateModel(
            name='ProposalExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('tx_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('meta_hash', models.CharField(blank=True, max_length=64)),
                ('evidence_json', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='governance.proposal')),
            ],
        ),
    ]
