# Generated by Django 3.2.25 on 2026-03-10 07:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('governance', '0025_zero_aqua_supply_for_proposal_125'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='onchain_action_args',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_action_type',
            field=models.CharField(
                choices=[
                    ('NONE', 'No onchain action'),
                    ('ADD_ASSET', 'Add asset'),
                    ('REMOVE_ASSET', 'Remove asset'),
                ],
                default='NONE',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_status',
            field=models.CharField(
                choices=[
                    ('NOT_REQUIRED', 'No execution required'),
                    ('PENDING', 'Pending execution'),
                    ('SUCCESS', 'Execution succeeded'),
                    ('FAILED', 'Execution failed'),
                    ('SKIPPED', 'Execution skipped'),
                ],
                default='NOT_REQUIRED',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_tx_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
