# Generated by Codex on 2026-04-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0026_proposal_asset_governance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={
                'permissions': [
                    ('manage_asset_proposals', 'Can manage asset proposals in admin'),
                ],
            },
        ),
    ]
