# Generated by Django 3.2.23 on 2026-03-17 12:22

from django.db import migrations, models


def set_asset_proposal_type_for_onchain_records(apps, schema_editor):
    Proposal = apps.get_model('governance', 'Proposal')
    Proposal.objects.exclude(onchain_action_type='NONE').update(proposal_type='ASSET')


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0026_proposal_onchain_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='asset_aquarius_traction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_audit_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_community_references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_contract_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_holder_distribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_issuer',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_issuer_commitments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_issuer_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_liquidity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_related_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_stellar_flags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_token_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='asset_trading_volume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('GENERAL', 'General proposal'), ('ASSET', 'Asset proposal')], db_index=True, default='GENERAL', max_length=32),
        ),
        migrations.RunPython(set_asset_proposal_type_for_onchain_records, migrations.RunPython.noop),
    ]
