# Generated by Django 3.2.23 on 2026-03-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0027_auto_20260317_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='onchain_execution_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'No execution required'), ('PENDING', 'Pending execution'), ('IN_PROGRESS', 'Execution in progress'), ('SUBMITTED', 'Transaction submitted'), ('SUCCESS', 'Execution succeeded'), ('FAILED', 'Execution failed'), ('SKIPPED', 'Execution skipped')], default='NOT_REQUIRED', max_length=32),
        ),
    ]
