# Generated by Django 3.2.25 on 2026-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0028_asset_token_and_proposal_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettoken',
            name='contract_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettoken',
            name='contract_sync_status',
            field=models.CharField(choices=[('SYNCED', 'Contract is up to date with DB state'), ('PENDING', 'Waiting for contract update'), ('FAILED', 'Contract update failed'), ('REQUIRES_REVIEW', 'Contract update requires manual review')], db_index=True, default='SYNCED', max_length=16),
        ),
        migrations.AddField(
            model_name='assettoken',
            name='contract_sync_tx_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='assettoken',
            name='contract_sync_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
