# Generated by Django 3.2.25 on 2026-03-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0028_alter_proposal_onchain_execution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_poll_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='onchain_execution_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='onchain_execution_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'No execution required'), ('PENDING', 'Pending execution'), ('IN_PROGRESS', 'Execution in progress'), ('SUBMITTED', 'Transaction submitted'), ('SUCCESS', 'Execution succeeded'), ('FAILED', 'Execution failed'), ('REQUIRES_REVIEW', 'Execution requires review'), ('SKIPPED', 'Execution skipped')], default='NOT_REQUIRED', max_length=32),
        ),
    ]
