# Generated by Django 3.2.25 on 2026-06-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0028_asset_token_and_proposal_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalQueueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(unique=True)),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_slot', to='governance.proposal')),
            ],
            options={
                'ordering': ['start_at', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_status',
            field=models.CharField(
                choices=[
                    ('DISCUSSION', 'Proposal under discussion'),
                    ('QUEUED', 'Proposal queued for voting'),
                    ('VOTING', 'Proposal under voting'),
                    ('VOTED', 'Voted'),
                    ('EXPIRED', 'Expired'),
                ],
                default='DISCUSSION',
                max_length=64,
            ),
        ),
    ]
