PROPOSAL_STATUS_DISCUSSION = 'DISCUSSION'
PROPOSAL_STATUS_QUEUED = 'QUEUED'
PROPOSAL_STATUS_VOTING = 'VOTING'
PROPOSAL_STATUS_VOTED = 'VOTED'
PROPOSAL_STATUS_EXPIRED = 'EXPIRED'

PROPOSAL_STATUS_CHOICES = (
    (PROPOSAL_STATUS_DISCUSSION, 'Proposal under discussion'),
    (PROPOSAL_STATUS_QUEUED, 'Proposal queued for voting'),
    (PROPOSAL_STATUS_VOTING, 'Proposal under voting'),
    (PROPOSAL_STATUS_VOTED, 'Voted'),
    (PROPOSAL_STATUS_EXPIRED, 'Expired'),
)

QUEUE_OCCUPYING_PROPOSAL_STATUSES = (
    PROPOSAL_STATUS_QUEUED,
    PROPOSAL_STATUS_VOTING,
)

PROPOSAL_ACTION_NONE = 'NONE'
PROPOSAL_ACTION_TO_UPDATE = 'TO_UPDATE'
PROPOSAL_ACTION_TO_SUBMIT = 'TO_SUBMIT'
PROPOSAL_ACTION_TO_CREATE = 'TO_CREATE'

PROPOSAL_ACTION_CHOICES = (
    (PROPOSAL_ACTION_TO_UPDATE, 'To update'),
    (PROPOSAL_ACTION_TO_SUBMIT, 'To submit'),
    (PROPOSAL_ACTION_TO_CREATE, 'To create'),
    (PROPOSAL_ACTION_NONE, 'None'),
)
